version: "3.0"
services:
  frps:
    build:
      context: .
      dockerfile: Dockerfileserver
    image: frps
    container_name: frps
    network_mode: host
    entrypoint: ["/root/frp/frp/frps","-c","/root/frp/frps.toml"]
